### PR TITLE
Add a prop to prevent scaling the canvas based on the device pixel ratio

### PR DESCRIPTION
**Pull request by aryehb**
The default behavior is to resize and scale the canvas up based on the device pixel ratio (using `window.devicePixelRatio`). For example, if the ratio is 3, the `width` and `height` of the canvas will be multiplied by 3. This causes the output to be 3x the size as well, which can be undesired.

This change adds a `scaleToDevicePixelRatio` prop, which defaults to `true`, but allows setting it to `false` which will prevent scaling the canvas.

### CODE REVIEW

**Comment by neighborhood999** [comment]
Looks great. Thanks for your contribution!

Current PR wants to merge into v2 branch, did you consider opening another PR for Vue 3?

**Comment by aryehb** [comment]
I'm still using Vue v2, and I don't have any experience with v3. Can you port it to v3?

**Comment by neighborhood999** [comment]
> I'm still using Vue v2, and I don't have any experience with v3. Can you port it to v3?

Actually, me too haha, but I think it can port to v3 directly.

**Comment by aryehb** [comment]
@neighborhood999 Can this PR be merged and a new v2 version released, independent of a v3 PR?

**Comment by neighborhood999** [comment]
> @neighborhood999 Can this PR be merged and a new v2 version released, independent of a v3 PR?

Yes, that's what I mean.

**Comment by neighborhood999** [comment]
I published [2.0.5-beta.1](https://www.npmjs.com/package/vue-signature-pad/v/2.0.5-beta.1), please check it.

If everything is okay, I will publish **2.0.5** version, Thanks.

**Comment by aryehb** [comment]
@neighborhood999 v2.0.5-beta.1 looks good to me. Thank you!

**Comment by neighborhood999** [comment]
> @neighborhood999 v2.0.5-beta.1 looks good to me. Thank you!

Nice, I published [v2.0.5](https://www.npmjs.com/package/vue-signature-pad/v/2.0.5)!
If you have feel time can help Vue3 is appreciated, otherwise, I will do it later.

**Pull request merged**
