### PR TITLE
feature(penColor): Add changePenColor method

### LINKED ISSUE #124: Cannot update penColor
Using v. 1.1.11 of vue-signature-pad.

Once my component mounts, I can no longer change the `penColor`: 
I have a color picker that returns a hex value:

```javascript
    <VueSignaturePad ref="signaturePad" :options="{ options }" />
    <ColorPicker @change="handleColorChange" />

```

```javascript
  data() {
    return {
      options: {
        minWidth: 0.5,
        maxWidth: 2.5,
        throttle: 16,
        minDistance: 5,
        backgroundColor: "white",
        penColor: "#000",
        velocityFilterWeight: 0.7
      }
    };
  },
  methods: {
    handleColorChange(value) {
      this.options.penColor = value;
    }
  }
```

The penColor stays what it was when I first initialize it. This is also true if I try a more direct approach:

```javascript
    <VueSignaturePad ref="signaturePad" :options="{ penColor }" />
    <q-btn @click="penColor = 'red'">Change Color</q-btn>
```

```javascript
  data() {
    return {
      penColor: 'black'
    };
  },
```

The options object is changing on the VueSignaturePad ref instance, but the outputted color stays the same.

### PR DESCRIPTION
**Pull request by andrewhl**
I just added the following method to `VueSignaturePad.js`:

```javascript
    changePenColor(color) {
      this.signaturePad.penColor = color;
    },
```

This is because I could not dynamically change the penColor after mounting. With this method I can do:

```this.$refs.signaturePad.changePenColor(newColor)```

I've tested it locally and it works.

Closes #124

### CODE REVIEW

**Comment by andrewhl** [comment]
I don't recommend actually merging this PR, since I probably stupidly ran `yarn dev:prod` and minified all the dist files. But if you could incorporate the change I made I would be thrilled.

**Comment by neighborhood999** [comment]
Hi @andrewhl 

Sorry for about this issue, I'm a long time didn't write Vue.

I think this method is not required, you can spread your `options` in the binding `:options`.

In your example, you can update your code following below and here is [example](https://codesandbox.io/s/vue-signature-pad-demo-toy9p):

```vue
<VueSignaturePad ref="signaturePad" :options="{ ...options }" />
```

**Comment by andrewhl** [comment]
@neighborhood999 Hello! Thank you for your response. I tried to do what you suggested, and it still doesn't update the color. Here is my code:

```vue
<template>
  <div class="DrawingPad">
    <VueSignaturePad ref="signaturePad" :options="{ ...options }" />
    <ColorPicker @change="handleColorChange" />
    <q-btn @click="save">Save</q-btn>
  </div>
</template>

<script>
import VueSignaturePad from "vue-signature-pad";
import ColorPicker from "components/ColorPicker";

export default {
  name: "DrawingPad",
  components: {
    VueSignaturePad,
    ColorPicker
  },
  data() {
    return {
      options: {
        minWidth: 0.5,
        maxWidth: 2.5,
        throttle: 16,
        minDistance: 5,
        backgroundColor: "white",
        penColor: "#000",
        velocityFilterWeight: 0.7
      }
    };
  },
  methods: {
    handleColorChange(value) {
      this.options = {
        ...this.options,
        penColor: value
      };
    },
    save() {
      this.$refs.signaturePad.saveSignature();
    }
  }
};
</script>
```

I have also attempted to update the `penColor` directly:

```vue
    handleColorChange(value) {
     this.options.penColor = value;
    },
```

Please advise. Thank you!

**Comment by neighborhood999** [comment]
I think the right way is adding some method like `updated` inside the component. If I want to update other options, it will add more like `handleXXX` functions.

**Comment by neighborhood999** [comment]
@andrewhl Because options are `mounted` with instance, so I think a good way is refactoring here, we can dynamically change options and update the signature style. The [updated](https://vuejs.org/v2/api/#updated) means Vue's lifecycle function.

**Comment by andrewhl** [comment]
@neighborhood999 Can you provide some guidance on how you would implement this? I tried the following:

```javascript
  updated() {
    this.$nextTick(function() {
      this.signaturePad.penColor = this.color;
    });
  },
```

But it doesn't work when I try this in the component view:

```vue
    <VueSignaturePad
      ref="signaturePad"
      :color="options.penColor"
      :options="{
        penColor: options.penColor,
        minDistance: options.minDistance,
        maxWidth: options.maxWidth,
        minWidth: options.minWidth,
        onBegin,
        onEnd
      }"
    />
```

Modifying the 'options' data property doesn't result in rerendering the component. I also tried not using this.$nextTick:

```javascript
  updated() {
    this.signaturePad.penColor = this.color;
  },
```

Also has no effect. Help would be appreciated.

**Comment by neighborhood999** [comment]
Hi @andrewhl 

Sorry, I'm a long time didn't write Vue. Above suggestion just my concept. Today I took look Vue docs, I found [sync modifier](https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier), not sure this can solve this problem. I will try this in my free time.

**Comment by neighborhood999** [comment]
I created [branch](https://github.com/neighborhood999/vue-signature-pad/tree/fix/dynamic-change-options) to fix, you can try it.

**Comment by neighborhood999** [comment]
I created the [branch](https://github.com/neighborhood999/vue-signature-pad/tree/fix/dynamic-change-options) to fix, you can try it.

**Comment by andrewhl** [comment]
By the way, I tried it out and could not get it to work properly. I’ll post my code shortly.

**Pull request closed without merging**
